import { notFound } from "next/navigation";
import { LABS } from "@/data/labs";
import PlannedLabPage from "@/labs/PlannedLabPage";

// ── Live labs ──────────────────────────────────────────────────────────────────
import Univac9 from "@/labs/Univac9";
import DeepLearning9 from "@/labs/DeepLearning9";
import Gpu9 from "@/labs/Gpu9";
import Cloudflare9 from "@/labs/Cloudflare9";
import VirtualMem9 from "@/labs/VirtualMem9";
import SpectreMeltdown9 from "@/labs/SpectreMeltdown9";
import EthereumDao9 from "@/labs/EthereumDao9";
import QuantumComputing9 from "@/labs/QuantumComputing9";
import AsymmetricCrypto9 from "@/labs/AsymmetricCrypto9";
import RequirementsAnalysis9 from "@/labs/RequirementAnalysis9";
import HashFunctions9 from "@/labs/HashFunctions9";
import SymmetricCrypto9 from "@/labs/SymmetricCrypto9";
import MachineLearning9 from "@/labs/MachineLearning9";
import Blockchain9 from "@/labs/Blockchain9";
import ClassesInJava9 from "@/labs/ClassesInJava9";
import AlgorithmicMusic9 from "@/labs/AlgorithmicMusic9";
import ManInTheMiddle9 from "@/labs/ManInTheMiddle9";
import Ransomware9 from "@/labs/Ransomware9";
import BrainComputerInterface9 from "@/labs/BrainComputerInterface9";
import PasswordCracking9 from "@/labs/PasswordCracking9";
import BufferOverflow9 from "@/labs/BufferOverflow9";
import FoldableSmartphone11 from "@/labs/FoldableSmartphone11";
import AIEducation22 from "@/labs/AIEducation22";
import ResponsibleAI23 from "@/labs/ResponsibleAI23";
import AdvancedAlgorithms24 from "@/labs/AdvancedAlgorithms24";
import USBConnectivity25 from "@/labs/USBConnectivity25";
import SetsAndVenn27 from "@/labs/SetsAndVenn27";
import NetworkInterface31 from "@/labs/NetworkInterface31";
import DataVisualization36 from "@/labs/DataVisualization36";
import MobilePlatform37 from "@/labs/MobilePlatform37";
import BinarySearch12 from "@/labs/BinarySearch12";
import OopPython15 from "@/labs/OopPython15";
import CloudStrategy16 from "@/labs/CloudStrategy16";
import ITSupport18 from "@/labs/ITSupport18";
import AGIInterview19 from "@/labs/AGIInterview19";
import CrossSiteScripting9 from "@/labs/CrossSiteScripting9";
import TorRouting9 from "@/labs/TorRouting9";
import Microservices9 from "@/labs/Microservices9";
import ZeroDayExploit9 from "@/labs/ZeroDayExploit9";
import MachineLearningTraining9 from "@/labs/MachineLearningTraining9";
import ContentDeliveryNetwork9 from "@/labs/ContentDeliveryNetwork9";
import GraphQLBasics9 from "@/labs/GraphQLBasics9";
import RateLimiting9 from "@/labs/RateLimiting9";
import SshKeys9 from "@/labs/SshKeys9";
import Colossus28 from "@/labs/Colossus28";
import OauthFlow9 from "@/labs/OauthFlow9";
import SmartRing32 from "@/labs/SmartRing32";
import WebAssembly9 from "@/labs/WebAssembly9";
import JwtTokens9 from "@/labs/JwtTokens9";
import ComputingProject39 from "@/labs/ComputingProject39";
import GestureControl40 from "@/labs/GestureControl40";
import ContinuousIntegration9 from "@/labs/ContinuousIntegration9";
import ReverseProxies9 from "@/labs/ReverseProxies9";
import CsrfAttacks9 from "@/labs/CsrfAttacks9";
import ComputingBenefits44 from "@/labs/ComputingBenefits44";
import SemanticWeb45 from "@/labs/SemanticWeb45";
import RoboticSurgery46 from "@/labs/RoboticSurgery46";
import PropositionalLogic42 from "@/labs/PropositionalLogic42";
import TestingStrategies43 from "@/labs/TestingStrategies43";

export function generateStaticParams() {
  // Next.js 16 can race while rewriting the development prerender manifest
  // when several lab routes are opened together. Render labs on demand in dev;
  // production builds should continue to pre-render the complete lab catalog.
  if (process.env.NODE_ENV === "development") return [];

  return LABS.map((lab) => ({ slug: lab.slug }));
}

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const lab = LABS.find((item) => item.slug === slug);
  if (!lab) notFound();

  if (slug === "univac9") return <Univac9 />;
  if (slug === "deeplearning9") return <DeepLearning9 />;
  if (slug === "gpu9") return <Gpu9 />;
  if (slug === "cloudflare9") return <Cloudflare9 />;
  if (slug === "virtualmem9") return <VirtualMem9 />;
  if (slug === "spectremeltdown9") return <SpectreMeltdown9 />;
  if (slug === "ethereumdao9") return <EthereumDao9 />;
  if (slug === "quantumcomputing9") return <QuantumComputing9 />;
  if (slug === "asymmetriccrypto9") return <AsymmetricCrypto9 />;
  if (slug === "requirementsanalysis9") return <RequirementsAnalysis9 />;
  if (slug === "hashfunctions9") return <HashFunctions9 />;
  if (slug === "symmetriccrypto9") return <SymmetricCrypto9 />;
  if (slug === "machinelearning9") return <MachineLearning9 />;
  if (slug === "blockchain9") return <Blockchain9 />;
  if (slug === "classesinjava9") return <ClassesInJava9 />;
  if (slug === "algorithmicmusic9") return <AlgorithmicMusic9 />;
  if (slug === "maninthemiddle9") return <ManInTheMiddle9 />;
  if (slug === "ransomware9") return <Ransomware9 />;
  if (slug === "braincomputerinterface9") return <BrainComputerInterface9 />;
  if (slug === "passwordcracking9") return <PasswordCracking9 />;
  if (slug === "bufferoverflow9") return <BufferOverflow9 />;
  if (slug === "foldablesmartphone11") return <FoldableSmartphone11 />;
  if (slug === "binarysearch12") return <BinarySearch12 />;
  if (slug === "ooppython15") return <OopPython15 />;
  if (slug === "cloudstrategy16") return <CloudStrategy16 />;
  if (slug === "itsupport18") return <ITSupport18 />;
  if (slug === "agiinterview19") return <AGIInterview19 />;
  if (slug === "aieducation22") return <AIEducation22 />;
  if (slug === "responsibleai23") return <ResponsibleAI23 />;
  if (slug === "advancedalgorithms24") return <AdvancedAlgorithms24 />;
  if (slug === "usbconnectivity25") return <USBConnectivity25 />;
  if (slug === "setsandvenn27") return <SetsAndVenn27 />;
  if (slug === "networkinterface31") return <NetworkInterface31 />;
  if (slug === "datavisualization36") return <DataVisualization36 />;
  if (slug === "mobileplatform37") return <MobilePlatform37 />;
  if (slug === "crosssitescripting9") return <CrossSiteScripting9 />;
  if (slug === "torrouting9") return <TorRouting9 />;
  if (slug === "microservices9") return <Microservices9 />;
  if (slug === "zerodayexploit9") return <ZeroDayExploit9 />;
  if (slug === "machinelearningtraining9") return <MachineLearningTraining9 />;
  if (slug === "contentdeliverynetwork9") return <ContentDeliveryNetwork9 />;
  if (slug === "graphqlbasics9") return <GraphQLBasics9 />;
  if (slug === "ratelimiting9") return <RateLimiting9 />;
  if (slug === "sshkeys9") return <SshKeys9 />;
  if (slug === "colossus28") return <Colossus28 />;
  if (slug === "oauthflow9") return <OauthFlow9 />;
  if (slug === "smartring32") return <SmartRing32 />;
  if (slug === "webassembly9") return <WebAssembly9 />;
  if (slug === "jwttokens9") return <JwtTokens9 />;
  if (slug === "computingproject39") return <ComputingProject39 />;
  if (slug === "continuousintegration9") return <ContinuousIntegration9 />;
  if (slug === "reverseproxies9") return <ReverseProxies9 />;
  if (slug === "gesturecontrol40") return <GestureControl40 />;
  if (slug === "csrfattacks9") return <CsrfAttacks9 />;
  if (slug === "computingbenefits44") return <ComputingBenefits44 />;
  if (slug === "semanticweb45") return <SemanticWeb45 />;
  if (slug === "roboticsurgery46") return <RoboticSurgery46 />;
  if (slug === "propositionallogic42") return <PropositionalLogic42 />;
  if (slug === "testingstrategies43") return <TestingStrategies43 />;

  return <PlannedLabPage lab={lab} />;
}
